# Intialisation Steps
Connecting to Snowflake

## Importing required modules

In [2]:
import pandas as pd
from drg_connect import Snowflake
import qgrid 
from datetime import timedelta, datetime
import math

import warnings
warnings.filterwarnings('ignore')

## Snowflake connection parameter

In [3]:
##defining parameters of snowflake
snow = Snowflake(role = 'RWD_ANALYTICS_RW',database='SANDBOX_ANALYTICS',schema = 'SANDBOX')
engine = snow.engine

%reload_ext sql_magic
%config SQL.output_result = True  #Enable output to std out
%config SQL.notify_result = False #disable browser notifications
%config SQL.conn_name = 'engine'  #Set the sql_magic connection engine

# Queries from here

# Pelican EHR data

## Pelican table details

In [3]:
%%read_sql

select * from RWD_DB.RWD.PELICAN_E_LOINC limit 3

Query started at 04:50:17 PM India Standard TimeInitiating login request with your identity provider. A browser window should have opened for you to complete the login. If you can't see it, check existing browser windows, or your OS settings. Press CTRL+C to abort and try again...
; Query executed in 0.39 m

,loinc_num,component,property,time_aspct,system,scale_typ,method_typ,class,last_modified,chng_type,...,document_section,example_ucum_units,example_si_ucum_units,status_reason,status_text,change_reason_public,common_test_rank,common_order_rank,common_si_test_rank,hl7_attachment_structure
0,9256-9,Fluid output.total,Vol,Pt,^Patient,Qn,Estimated,IO_OUT.ATOM,1996-09-06,ADD,...,None,None,None,None,None,None,0,0,0,None
1,38474-3,Acylcarnitine,SCnc,Pt,Bld.dot,Qn,None,CHEM,2008-10-21,NAM,...,None,umol/L,None,None,None,None,0,0,0,None
2,2404-2,Hemopexin,MCnc,Pt,Urine,Qn,None,CHEM,2006-10-26,MAJ,...,None,mg/dL,None,None,None,None,0,0,0,None

In [4]:
%%read_sql

select * from RWD_DB.RWD.PELICAN_LABORDER limit 3

Query started at 04:54:02 PM India Standard Time; Query executed in 0.14 m

,laborder_id,patient_id,provider_id,vendor_id,loinc_num,result_status,report_date,observed_at,obs_quan,obs_qual,unit,is_abnormal,abnormal_flag,created_at,last_modified,transcript_id
0,1364935398341433546,393E2EED-4D2C-79C7-D150-08E8154D142F,None,8844736773880785995,2160-0,Final,2015-11-08,2015-11-14,0.96,NaN,mg/dL,None,None,2015-11-14,2015-11-14,None
1,4177387127494394539,393E2EED-4D2C-79C7-D150-08E8154D142F,D8E5640E-9F96-E7A1-BA57-6E996DF43374,8844736773880785995,43396-1,Final,2018-07-31,2018-08-04,212.00,NaN,mg/dL (calc),None,None,2018-08-05,2018-08-05,None
2,-8421755992989376358,393E2EED-4D2C-79C7-D150-08E8154D142F,D8E5640E-9F96-E7A1-BA57-6E996DF43374,8844736773880785995,30446-9,Not available,2018-07-31,2018-08-04,NaN,281266006.0,cells/uL,None,None,2018-08-05,2018-08-05,None

## Corresponding loinc codes for triglycerides

### Things to remember about loinc codes
 - Format: nnnnn-n
 - Component: what was measured
 - Unit: check from laborder table
 - date: ask/confirm which date to use - report date or observed_at date
 - there's no 'component' variable in laborder table so create an excel for loinc codes and upload

In [15]:
%%read_sql

create or replace table st_ref_loinc as

    select
        loinc_num,
        component

    from RWD_DB.RWD.PELICAN_E_LOINC
    
    where component ilike '%triglyceride%'
        or component ilike '%hdl%'
        or component ilike '%cholesterol%'
        and not component ilike '%ldl%'

Query started at 08:03:17 PM India Standard Time; Query executed in 0.13 m

                                     status
0  Table ST_REF_LOINC successfully created.

In [16]:
snow.select("select * from st_ref_loinc")

    loinc_num                                          component
0      2086-7                                 Cholesterol.in HDL
1     50223-7                               Cholesterol crystals
2      2087-5                                 Cholesterol.in IDL
3     57937-5                              Cholesterol.in HDL 3a
4     32289-1                               7-Dehydrocholesterol
5     17081-1                             Triglyceride^post CFst
6     34472-1                               Cholesterol crystals
7     35200-5                                        Cholesterol
8      2565-0                                        Cholesterol
9     14438-6                                        Cholesterol
10    14447-7                                       Triglyceride
11    74433-4                            Cholestanol/Cholesterol
12    18263-4                                 Cholesterol.in HDL
13    14154-9                                Cholesterol sulfate
14     5777-8                               Cholesterol crystals
15    28554-4                                       Triglyceride
16    53527-8                              Triglyceride.in HDL 2
17     2094-1                         Cholesterol.non-esterified
18    70260-5        Triglyceride.periton fld/Triglyceride.serum
19    59250-1                            Tocopherols/Cholesterol
20    16616-5              Cholesterol.in HDL/Cholesterol.in LDL
21    70269-6            Triglyceride.plr fld/Triglyceride.serum
22    35197-3                                 Cholesterol.in HDL
23    59571-0                                       Triglyceride
24     3047-8                         Triglyceride+ester.in VLDL
25    27340-9                                 Cholesterol.in HDL
26     2093-3                                        Cholesterol
27    57936-7                              Cholesterol.in HDL 2a
28    50799-6                               7-Dehydrocholesterol
29     9619-8                                       Triglyceride
..        ...                                                ...
145   21197-9               Cholesterol esters/Cholesterol.total
146   32308-9                                        Cholesterol
147   25153-8                               Cholesterol crystals
148   74359-1   Cholesterol ester transfer protein actual/normal
149   53082-4                                        Cholesterol
150   70204-3                                Cholesterol.non HDL
151    5932-9                                        Cholesterol
152   70268-8              Cholesterol.plr fld/Cholesterol.serum
153   48620-9                                        Cholesterol
154   73852-6  7-Dehydrocholesterol & 8-Dehydrocholesterol panel
155   14449-3                                       Triglyceride
156   53528-6                              Triglyceride.in HDL 3
157   12531-0                                        Cholesterol
158   54373-6                         Cholesterol.non-esterified
159   46700-1                               7-Dehydrocholesterol
160   44915-7              Cholesterol.in LDL/Cholesterol.in HDL
161   56035-9              Apolipoprotein A-I/Cholesterol.in HDL
162   54469-2     Cholesterol.in HDL 3a/Cholesterol.in HDL.total
163   35361-5             Triglyceride.in lipoprotein (little a)
164   14439-4                                        Cholesterol
165   48089-7                       Cholesterol/Apolipoprotein B
166   16614-0                               Cholesterol crystals
167   59038-0                                        Cholesterol
168   55839-5                 Cholesterol ester transfer protein
169   54371-0                                        Cholesterol
170   35389-6                        Cholesterol.in chylomicrons
171    3044-5                          Triglyceride+ester.in HDL
172   66769-1                                       Triglyceride
173   58299-9  Age began taking high blood cholesterol medica...
174   50339-1                                        Cholesterol

[175 rows x 2 columns]

In [12]:
%%read_sql

create or replace temporary table st_loinc_ref1 as

select
    'loinc' as cat1,
     loinc_num as value,
    RELATEDNAMES2 as description,
    current_date() as active_date,
    'swar' as active_reason,
    null as deactive_date,
    null as deactive_reason,
    'RWD_DB.RWD.PELICAN_E_LOINC' as source
from 
   RWD_DB.RWD.PELICAN_E_LOINC
    where
        component ilike '%triglyceride%'

Query started at 02:13:19 PM India Standard Time; Query executed in 0.09 m

                                      status
0  Table ST_LOINC_REF1 successfully created.

In [13]:
%%read_sql df

select * from st_loinc_ref1

Query started at 02:15:35 PM India Standard Time; Query executed in 0.07 m

,cat1,value,description,active_date,active_reason,deactive_date,deactive_reason,source
0,loinc,17081-1,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
1,loinc,14447-7,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
2,loinc,28554-4,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
3,loinc,53527-8,Trigl in HDL2; TG; Trigly; Triglycrides; Trig;...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
4,loinc,70260-5,Trigl Prt; PT-TRIG; TG; Trigly; Triglycrides; ...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
5,loinc,70269-6,Trigl Plr fld; PF-TRIG; TG; Trigly; Triglycrid...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
6,loinc,59571-0,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
7,loinc,3047-8,Trigl+VLDL Ester; TG; Trigly; Triglycrides; Tr...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
8,loinc,9619-8,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
9,loinc,2096-6,Cholest; Chol; Choles; Lipid; Cholesterol tota...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
10,loinc,2571-8,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
11,loinc,3046-0,Trigl+LDL Ester; TG; Trigly; Triglycrides; Tri...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
12,loinc,55607-6,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
13,loinc,22731-4,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
14,loinc,69947-0,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
15,loinc,59572-8,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
16,loinc,34695-7,VLDLc; Very low density lipoprotein cholestero...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
17,loinc,35360-7,Lpa Trigl; Lpa Triglyceride; LP(a) Triglycerid...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
18,loinc,12951-0,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
19,loinc,3049-4,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
20,loinc,44718-5,VLDL; Very low density lipoproteins; Trigl; TG...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
21,loinc,3048-6,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
22,loinc,14445-1,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
23,loinc,1644-4,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
24,loinc,44733-4,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
25,loinc,30570-6,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
26,loinc,47210-0,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
27,loinc,12950-2,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
28,loinc,14446-9,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
29,loinc,30524-3,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
30,loinc,14927-8,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
31,loinc,14450-1,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
32,loinc,13899-0,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
33,loinc,29766-3,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
34,loinc,70218-3,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
35,loinc,39801-6,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
36,loinc,3045-2,Trigl+IDL Ester; Beta VLDL; TG; Trigly; Trigly...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
37,loinc,35363-1,Trig in Chylo; Trigl; TG; Trigly; Triglycrides...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
38,loinc,53526-0,Trigl in VLDL; TG; Trigly; Triglycrides; Trig;...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
39,loinc,35362-3,Trig in Chylo; Trigl; TG; Trigly; Triglycrides...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
40,loinc,70259-7,Trigl Pcar; PC-TRIG; TG; Trigly; Triglycrides;...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
41,loinc,59036-4,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
42,loinc,14448-5,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
43,loinc,12228-3,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
44,loinc,51605-4,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
45,loinc,3043-7,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
46,loinc,35217-9,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
47,loinc,14449-3,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
48,loinc,53528-6,Trigl in HDL3; TG; Trigly; Triglycrides; Trig;...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
49,loinc,35361-5,Lpa Trigl; Lpa Triglyceride; LP(a) Triglycerid...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
50,loinc,3044-5,Trigl+HDL Ester; TG; Trigly; Triglycrides; Tri...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC
51,loinc,66769-1,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,None,None,RWD_DB.RWD.PELICAN_E_LOINC

In [14]:
# Export to check, and then will inactivate codes that are not relevant and re-upload as final reference table
df.to_excel("out/loinccodes_check.xlsx", index=False)

## Upload into snowflake

In [15]:
loinc_ref = pd.read_excel("in/loinc_ref.xlsx")

In [17]:
snow.drop_table("st_loinc_ref")

DROP TABLE IF EXISTS sandbox_analytics.sandbox.st_loinc_ref;
Table sandbox.st_loinc_ref dropped!

In [18]:
snow.upload_dataframe(loinc_ref, "st_loinc_ref")

Upload successful!

In [19]:
%%read_sql

select *
from st_loinc_ref
where deactive_date is not null

Query started at 05:48:41 PM India Standard Time; Query executed in 0.07 m

,cat1,value,description,active_date,active_reason,deactive_date,deactive_reason,source
0,loinc,9619-8,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,2018-10-12,Triglyceride [Mass/volume] in Pleural fluid,RWD_DB.RWD.PELICAN_E_LOINC
1,loinc,2096-6,Cholest; Chol; Choles; Lipid; Cholesterol tota...,2018-12-10,swar,2018-10-12,cholesterol levels?,RWD_DB.RWD.PELICAN_E_LOINC
2,loinc,34695-7,VLDLc; Very low density lipoprotein cholestero...,2018-12-10,swar,2018-10-12,Cholesterol.in VLDL/Triglyceride,RWD_DB.RWD.PELICAN_E_LOINC
3,loinc,44718-5,VLDL; Very low density lipoproteins; Trigl; TG...,2018-12-10,swar,2018-10-12,Lipoprotein.pre-beta/Triglyceride [Mass Ratio]...,RWD_DB.RWD.PELICAN_E_LOINC
4,loinc,44733-4,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,2018-10-12,Trigl/HDLc SerPl,RWD_DB.RWD.PELICAN_E_LOINC
5,loinc,70259-7,Trigl Pcar; PC-TRIG; TG; Trigly; Triglycrides;...,2018-12-10,swar,2018-10-12,Pericardial fluid to serum tryglyceride ratio ...,RWD_DB.RWD.PELICAN_E_LOINC
6,loinc,59036-4,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,2018-10-12,Triglyceride [Mass/volume] in Peritoneal dialy...,RWD_DB.RWD.PELICAN_E_LOINC
7,loinc,14448-5,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,2018-10-12,Triglyceride [Mass/volume] in Semen,RWD_DB.RWD.PELICAN_E_LOINC
8,loinc,51605-4,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,2018-10-12,Triglyceride [Moles/volume] in Synovial fluid,RWD_DB.RWD.PELICAN_E_LOINC
9,loinc,14449-3,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,2018-10-12,Triglyceride [Mass/volume] in Synovial fluid,RWD_DB.RWD.PELICAN_E_LOINC
10,loinc,35361-5,Lpa Trigl; Lpa Triglyceride; LP(a) Triglycerid...,2018-12-10,swar,2018-10-12,Triglyceride in lipoprotein a [Presence] in Se...,RWD_DB.RWD.PELICAN_E_LOINC
11,loinc,66769-1,Trigl; TG; Trigly; Triglycrides; Trig; Triglyc...,2018-12-10,swar,2018-10-12,Triglyceride [Moles/volume] in Peritoneal fluid,RWD_DB.RWD.PELICAN_E_LOINC

## Using laborders table

### Things to do:
    - We want unique patients related to the above listed loinc codes.
    - We then want to stratify them into buckets (see image in next section)

In [24]:
%%html
<img src="img/analysis_plan.png", width=800, height=800)>

## Observation cohort

In [27]:
%%read_sql

create or replace table st_tg_obs_cohort as

select
    patient_id,
    loinc_num,
    result_status,
    report_date,
    observed_at,
    obs_quan,
    obs_qual,
    unit,
    last_modified

from
    RWD_DB.RWD.PELICAN_LABORDER
where
    loinc_num in (select value from st_loinc_ref where cat1 = 'loinc' and deactive_date is null)

Query started at 06:32:39 PM India Standard Time; Query executed in 0.55 m

                                         status
0  Table ST_TG_OBS_COHORT successfully created.

In [28]:
snow.select("select count(distinct patient_id) from st_tg_obs_cohort where left(patient_id, 5) != 'XXX -'")

   COUNT(DISTINCT PATIENT_ID)
0                     6461414

In [29]:
%%read_sql
select * from st_tg_obs_cohort limit 100

Query started at 06:38:45 PM India Standard Time; Query executed in 0.12 m

,patient_id,loinc_num,result_status,report_date,observed_at,obs_quan,obs_qual,unit,last_modified
0,1ED968AE-FE37-9FDD-975C-3A01C5105818,2571-8,Final,2016-01-06,2016-01-05,201.0,None,mg/dL,2016-01-06
1,6085D796-747B-F408-0DAF-D5A10557EC1B,2571-8,Final,2016-12-16,2016-12-15,53.0,None,mg/dL,2016-12-16
2,BEB71C61-A885-8E9A-832F-739ACCD7E866,2571-8,Final,2013-10-18,2013-10-18,247.0,None,mg/dL,2015-09-19
3,56C97897-7D46-CD67-6FA8-F64E25EF7288,2571-8,Final,2017-11-03,2017-11-03,104.0,None,mg/dL,2017-11-03
4,23651DE6-800F-8681-43E0-FDC1149FA0F3,2571-8,Final,2015-05-02,2015-05-01,93.0,None,mg/dL,2015-09-10
5,342B4281-B2C2-C328-13AC-5A6E8B6531EF,2571-8,Final,2015-09-02,2015-09-04,123.0,None,mg/dL,2015-09-04
6,260C059C-AE07-DA2F-29B8-1ACAFA737221,2571-8,Final,2018-02-08,2018-02-08,212.0,None,mg/dL,2018-02-08
7,260C059C-AE07-DA2F-29B8-1ACAFA737221,2571-8,Final,2017-01-30,2017-01-22,186.0,None,mg/dL,2017-02-01
8,90C8E9DB-1A46-B5CE-1EA3-1DB1C404BD2C,2571-8,Final,2017-09-03,2017-09-04,501.0,None,mg/dL,2017-09-04
9,65AFC983-5495-1CDB-5D2B-C4F0B2DD5BBD,12951-0,Final,2016-06-12,2016-06-12,226.0,None,mg/dL,2016-06-12
10,65AFC983-5495-1CDB-5D2B-C4F0B2DD5BBD,12951-0,Final,2015-12-07,2015-12-06,234.0,None,mg/dL,2015-12-07
11,65AFC983-5495-1CDB-5D2B-C4F0B2DD5BBD,12951-0,Final,2013-04-14,None,209.0,None,mg/dL,2015-09-09
12,65AFC983-5495-1CDB-5D2B-C4F0B2DD5BBD,12951-0,Final,2014-07-21,None,166.0,None,mg/dL,2015-09-09
13,65AFC983-5495-1CDB-5D2B-C4F0B2DD5BBD,12951-0,Final,2012-09-25,None,159.0,None,mg/dL,2015-09-09
14,65AFC983-5495-1CDB-5D2B-C4F0B2DD5BBD,12951-0,Final,2014-10-28,2014-10-27,190.0,None,mg/dL,2015-09-19
15,65AFC983-5495-1CDB-5D2B-C4F0B2DD5BBD,12951-0,Final,2014-01-17,None,218.0,None,mg/dL,2015-09-09
16,F63D6638-B7C2-7BE0-522C-D86877B37FEA,2571-8,Final,2018-06-20,2018-06-19,224.0,None,MG/DL,2018-06-20
17,F63D6638-B7C2-7BE0-522C-D86877B37FEA,2571-8,Final,2016-10-17,2016-10-17,144.0,None,MG/DL,2016-10-17
18,23B5A131-E314-694D-A2C8-9F21AA6390E5,2571-8,Final,2018-05-25,2018-05-23,82.0,None,mg/dL,2018-05-25
19,23B5A131-E314-694D-A2C8-9F21AA6390E5,2571-8,Final,2013-03-30,2013-03-30,85.0,None,mg/dL,2015-09-13
20,23B5A131-E314-694D-A2C8-9F21AA6390E5,2571-8,Final,2016-12-02,2016-11-30,61.0,None,mg/dL,2016-12-06
21,23B5A131-E314-694D-A2C8-9F21AA6390E5,2571-8,Final,2016-05-28,2016-05-27,118.0,None,mg/dL,2016-05-31
22,23B5A131-E314-694D-A2C8-9F21AA6390E5,2571-8,Final,2016-02-27,2016-02-27,159.0,None,mg/dL,2016-05-31
23,23B5A131-E314-694D-A2C8-9F21AA6390E5,2571-8,Final,2015-05-28,2015-05-22,127.0,None,mg/dL,2015-09-11
24,23B5A131-E314-694D-A2C8-9F21AA6390E5,2571-8,Final,2014-10-04,2014-10-04,84.0,None,mg/dL,2015-09-13
25,BF9635EF-8A4A-8ABC-A84A-A60025205E94,2571-8,Final,2017-05-31,2017-05-30,50.0,None,mg/dL,2017-05-31
26,BF9635EF-8A4A-8ABC-A84A-A60025205E94,2571-8,Final,2017-05-31,2017-05-27,50.0,None,mg/dL,2017-05-31
27,0303951D-B00D-E4C2-F83B-03920E3010A2,2571-8,Final,2018-10-25,2018-10-25,102.0,None,MG/DL,2018-10-27
28,8CA2EA21-5021-B031-9106-056A6B3619CF,2571-8,Final,2018-06-17,2018-06-17,64.0,None,mg/dL,2018-06-17
29,1620E85C-768E-21B5-19E0-01967BA3D3D8,2571-8,Final,2013-09-10,2013-09-09,104.0,None,mg/dL,2015-09-08
...,...,...,...,...,...,...,...,...,...
70,4645778C-32EC-24E9-9BFE-65EE11770E7B,2571-8,Final,2012-06-19,2012-06-19,69.0,None,mg/dL,2015-09-20
71,4645778C-32EC-24E9-9BFE-65EE11770E7B,2571-8,Final,2013-01-09,2013-01-09,111.0,None,mg/dL,2015-09-20
72,4645778C-32EC-24E9-9BFE-65EE11770E7B,2571-8,Final,2015-02-26,2015-02-28,107.0,None,mg/dL,2015-09-11
73,4645778C-32EC-24E9-9BFE-65EE11770E7B,2571-8,Final,2013-07-29,2013-07-26,93.0,None,mg/dL,2015-09-20
74,074B6D7C-12DE-7AD1-9041-0B11AEFB81EA,2571-8,Final,2017-01-31,2017-01-31,134.0,None,mg/dL,2017-01-31
75,074B6D7C-12DE-7AD1-9041-0B11AEFB81EA,2571-8,Final,2017-11-27,2017-11-28,158.0,None,mg/dL,2017-11-28
76,074B6D7C-12DE-7AD1-9041-0B11AEFB81EA,2571-8,Final,2016-10-27,2016-10-27,180.0,None,mg/dL,2016-10-27
77,074B6D7C-12DE-7AD1-9041-0B11AEFB81EA,2571-8,Final,2018-06-15,2018-06-15,94.0,None,mg/dL,2018-06-15
78,074B6D7C-12DE-7AD1-9041-0B11AEFB81EA,2571-8,Final,2017-05-16,2017-05-16,172.0,None,mg/dL,2017-05-16
79,1FC920DB-49B4-EE77-BA71-B89E93CDFA71,2571-8,Final,2018-01-31,2018-01-24,111.0,None,mg/dL,2018-02-04
80,1FC920DB-49B4-EE77-BA71-B89E93CDFA71,2571-8,Final,2018-05-02,2018-04-30,84.0,None,mg/dL,2018-05-03
81,A0E0E8F2-0BB5-25D4-0BBC-6531D7666BAD,2571-8,Final,2017-11-04,2017-11-04,57.0,None,mg/dL,2017-11-04
82,D0AEE8A6-8B7F-BD59-FE99-DD9F44C492A5,2571-8,Final,2016-08-28,2016-08-28,69.0,None,mg/dL,2016-09-18
83,F81F4C80-AFFE-1A1D-4D82-ADBCDC92E597,2571-8,Final,2016-08-01,2016-08-02,51.0,None,mg/dL,2016-08-02
84,745CC5E9-AFC4-428E-6E74-1228906DEC4C,2571-8,Final,2018-03-31,2018-03-31,158.0,None,mg/dL,2018-03-31
85,D9B92AFF-A264-885D-E7FD-733E6A5E96B5,2571-8,Final,2017-06-18,2017-06-18,191.0,None,mg/dL,2017-06-18
86,9A7A0F75-A943-ECA7-8E3E-D98D5A342D6C,2571-8,Final,2014-08-05,2014-08-07,80.0,None,mg/dL,2015-09-17
87,54453904-45EC-E600-EFF4-48F0781F8EEB,2571-8,Final,2018-02-09,2018-02-09,69.0,None,mg/dL,2018-02-10
88,54453904-45EC-E600-EFF4-48F0781F8EEB,2571-8,Final,2018-09-04,2018-09-04,78.0,None,mg/dL,2018-09-04
89,54453904-45EC-E600-EFF4-48F0781F8EEB,2571-8,Final,2018-04-21,2018-04-21,74.0,None,mg/dL,2018-04-21
90,54453904-45EC-E600-EFF4-48F0781F8EEB,2571-8,Final,2018-10-27,2018-10-31,108.0,None,mg/dL,2018-11-02
91,54453904-45EC-E600-EFF4-48F0781F8EEB,2571-8,Final,2017-03-25,2017-03-25,129.0,None,mg/dL,2017-03-25
92,86C2F2BF-6044-BCDA-D6F6-9E8DFD7134B6,2571-8,Final,2013-08-10,2013-08-10,47.0,None,mg/dL,2015-09-09
93,86C2F2BF-6044-BCDA-D6F6-9E8DFD7134B6,2571-8,Final,2014-11-21,2014-11-21,46.0,None,mg/dL,2015-09-18
94,BE64F801-EAF9-C10F-CA73-62C12478D85A,2571-8,Final,2014-12-30,2014-12-26,62.0,None,mg/dL,2015-09-10
95,07A7E848-F5D1-2833-E85A-B660F23D4E72,2571-8,Final,2017-02-03,2017-02-02,108.0,None,mg/dL,2017-02-03
96,07A7E848-F5D1-2833-E85A-B660F23D4E72,2571-8,Final,2016-08-11,2016-08-11,109.0,None,mg/dL,2016-08-12
97,E3DE6EE7-500C-29B5-FE4A-B8A99C1C583C,2571-8,Final,2013-06-22,2013-06-22,177.0,None,mg/dL,2015-09-14
98,20104D2B-17E3-1CD8-4943-0E6E6F5315DB,2571-8,Final,2017-11-26,2017-11-28,114.0,None,mg/dL,2017-11-29
99,546527F1-0A5D-4FBC-D39B-B6A7F046CAFD,2571-8,Final,2013-01-21,2013-01-21,177.0,None,mg/dL,2015-09-09